global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    env: test
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
    scheme: http
    timeout: 10s
    api_version: v1
scrape_config_files:
  - 'targets_exporters.yml'
  - 'targets_services.yml'
rule_files:
  #  - 'alerts_services.yml'
  - 'alerts_exporters.yml'
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'tempo'
  static_configs:
  - targets: [ 'tempo:3200' ]
- job_name: mimir
  static_configs:
  - targets: ["mimir-1:8080"]
    labels:
      pod: "mimir-1"
  - targets: ["mimir-2:8080"]
    labels:
      pod: "mimir-2"
remote_write:
  - url: http://mimir-1:8080/api/v1/push
    headers:
      X-Scope-OrgID: demo

